name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.13']

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv sync
        uv add --dev pytest pytest-asyncio pytest-cov httpx

    - name: Download spaCy model for PII tests
      run: |
        uv run python -m spacy download fr_core_news_lg

    - name: Run fast tests
      run: |
        uv run pytest tests/ -v --tb=short

    - name: Run slow tests
      run: |
        uv run pytest tests/ --run-slow -v --tb=short
      continue-on-error: true

    - name: Generate coverage report
      run: |
        uv run pytest tests/ --cov=src --cov-report=xml --cov-report=html
      continue-on-error: true

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
      continue-on-error: true

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: pytest-results
        path: |
          htmlcov/
          .pytest_cache/
        retention-days: 30

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      run: uv python install 3.13

    - name: Install dependencies
      run: |
        uv sync
        uv add --dev ruff black mypy

    - name: Run ruff
      run: uv run ruff check src/ tests/
      continue-on-error: true

    - name: Run black
      run: uv run black --check src/ tests/
      continue-on-error: true

    - name: Run mypy
      run: uv run mypy src/
      continue-on-error: true
